language: android
notifications:
  email:
    recipients:
    - rowlandotienoo@gmail.com
    on_success: always
    on_failure: always
env:
  global:
  - secure: FgrUxMg0wBsJHlhhTeV0XFvB2oWHHG44oA3KxobP1H93Hd0X3gMrDLFPN2Cbt2XjCabfoN0S62V0TVXu0sVtmo4jiG1NL54i1kynM/lUXKvwb75K5W4x1gTGuDKnjMe1Hzb8qrgJBmq8oiWLo4kbUyFyWy/zuPyQ541dnEHZpDzII3UsWc2EQr4ifNsoDy6hDFiXd1KFFVqU3dN+hY69Ef+mpBxgLdoO6+iEZUg+Iv0cfXHl0U5YmwXpyA03D9nN80c3Ka8WRbryPRrG7OndRMUJOoSl+7CFXC6lbezTJ8JXqKqOP29fVG/oZmcoc2+754zvv6JQabfF0G2u1LApa3LeWpds+3li+3ZKdWMebmmT9Esnydb4/TCBR/e//yUJmDBsMdR08lwBg7h2njjx9QSDD9QpzF7rFcM+Ivm0wsvMdujL6skT7mLnkPuDXM9EI7RaZyHWiowcea3xo/XuolYC/nKmW7Cd0ahsfA1Awcg3bO9SqzL0JhrSgx1H1dTK/hyN6BnNCIbueZlvs+wsbkiBOxtY4+jWDe/+8rj4IPJH2Wl0ASCZC4urgLyGAKisSndGzneEhKeobZ3Yarj30Z0r7p3qOg63b+/edxeUJucI4efqLOXj4N49xLEjdSiFYCW2RKh8zfmJjq+YfLPfosT4PfiEVwuqphFS1Db9Yuw=
  - secure: 5FItsSmBKspv7A6lsCMUk7FtItif8sOPZmMFnmsSOGIznaiPvZRwORT4zfiHFo0HZQ4LbBVNVnbO7QDiXISyj4d3HbVT67IjWoFBtHyc1ctUxQFiUiwSc/0CUNlML2tiq13Z0pxYPYgZDupUVDoPCP+bKHXSZv+csthzbbz1iBO0sN0/xHBwfpXayNQccnTAs76b9By59T5HK6WQqLxCecDJcZl3WxPqHqye93fWIWgrJXsi3yMHJ+4AmxfyX+yTPTu20TkmFCwlUWEAI9TtHqNm354K18E/zzLPH5cfF7amEBYC3PLYrrBM3LytJ/TPmjZWHQ0fs8RqOAYXrdyaHA9CZvfrusIZ4Pggc/CIumAcxKPysmv0EUu1cXWdSZvP3xdCCNE60hkqyXEGl/PIehip2ZR86uKVSpIWmslxOXgmet4qN14vJz06XHf6HBabOODw7C2QDh81imLd8AcvA7cQcz4ie11UI+7TqOnjJl1PxCeS0L6pWX50uxvQI4RFjVHDKmdk8r8sFI3gH+xGF0BJCKRlZLJG914iA9c0Cut/V64VnrD20PATTZ7Kopi8G9m5g5e8yvvebcPxW8RUZ4HG8wZACw79xl/45UMw3nFWyRqPgrT+oIsef/5cslLfEqg2WraImbSOL+FUdN9XwCELdosHt0qRUQiBh+xHKZs=

jdk:
- oraclejdk8
android:
  components:
  - tools
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - build-tools-27.0.2
  - android-27
deploy:
  provider: releases
  # The api-key is encrypted like described here: http://docs.travis-ci.com/user/encryption-keys/  (only travis can decrypt the key)
  api_key:
    secure: N3g6uou0MlMpvP+oH1yF5+12G0uJgspmHU41+BHQR2/cUSKMRCw+vEjh8PJpQjWb7Jme+s+IZhUsDsmpT60FNL0cLeelsDn+R1t6XS1uIo6kK23R0p9FrKtth+IGUwAKnNNCkYnSB1TUglqjSbdCNL3PZRgfBwfB36QCu7VS3Uxyhy9o6j0PB3ImiCUsarYT1CYlxzdTkMNvxQSbcS6ze3gGeBtZ5JiZ7tOX8F+lYFQ9024/k/lyog8WH4wBa/rbpelDi0aOv3wEFjot0PT5KlEV4el6wYuFxzaADa8UGuKet45dIu1Bi4k8YjXylDmbPdPqRpUoy5YH/LpKUKsYac/pgB/trqSW9YqgIJ8xTdiGbewc/eiy3rNQxvn8TQL1lr7VSrPYIa2TVMuXxgTiVQ2glYbXs5IqH5rPpIu+vPLYCCBBMZ+5gHk+2b66iVmM2FpcgCo5SzNrsyJ39gwLuTI8RQ+CGMKyYV9XByzEcOQ3AaJBp1JcmS+MuplpaR1ZYlzg0+pGVmhAeJ0kBXv+9TMcyc9x0rKP6YrCNkU6Kh/iYtGlAuPHmJf77NPUuS2Sq/eZmZj5PoQfKG6Zpk6lUUHfQIviKtyTLce5/5/rjqxie7oOhOV0UUtSk3+aA/hmyhd7zAX9Yn33fPCn5ZvMf60cFPq2OFXQaznt/X3LVaE=
  # Which file(s) to upload
  file: sample/build/outputs/apk/debug/sample-debug.apk
  # do not delete the files we're trying to upload
  skip_cleanup: true
  # only deploy if
  on:
    # we are on this repo
    repo: RowlandOti/CartCounter
    # and we are building a tag
    tags: true
before_install:
- export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
- export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
- export JAVA_HOME=$JAVA8_HOME
- chmod +x gradlew
script:
- "./gradlew clean build --stacktrace"
after_deploy:
- "./gradlew bintrayUpload -PbintrayUser=$BINTRAYUSER -PbintrayKey=$BINTRAYKEY -PdryRun=false --stacktrace"