language: android
notifications:
  email:
    recipients:
    - rowlandotienoo@gmail.com
    on_success: always
    on_failure: always
env:
  global:
  - secure: a0ntodqya0a8584T2gTX06eLFGwxo/cBQ2lMowzHB5ELa9VwcvBrIROUDrLWwJu9HPk3EDHQDKnGPTkP9Cb7p3QjHY3oL0zvEJCfjGTszUQVEQBuVfK3uxKMeQhWzWexoOcCaHpbcBvQYRUBNwDBy+IrW6FOT6lFqS+7/eZiT9RvO59nxJxZ3q/HypIiYfQnoYl6dGEZeMpBrxJHQg2U+ZBSRf/yFFSrHQXRi5y/wK8zjrWpDjXVOYtzPv0DOdhCRVVx5M8LIWhq6LsZkWvdpAVJ4gCPEMM98rLQex32N+ZGp9gN9rymWJkdjuzKm3I72DOj059ALzSUuM5ySC4eYe/cHyTexfuQNb5JOMmCOZqccql6Id0s1xODC0sSL9IKxfXcQBNqvAA3/UUEu3bH+VB76m18Gkfv2XPfcHXMTiv6XyCiRPR3WdTvYAeCUkn4/YPKBXTovHr/xCqHIlRpor0CYj0f6ETa7fmf3UyK3KAj8ogK9G0vDgFJAWkFQ5OyDue+Yk2Prfv2U+pfkVFk+7hWWuVnHYBqDEwqdIGBpKUWxLLQOZuez3hUBLa/sDqZLBFWFyV/s026OfE+OXB+e/pNIxOKAwGuVCY9CuFSnGFnwZTi9pxFnI+mr4k91kc9fh9WHUGUqSEl5sXxDZ5iNozoIZbCSWdQDcRXC/qLLmU=
  - secure: T4Grbm3hASYRIUogx2eo+aNbMA3cK2eL0qhNpQKLlVwtm2C4kOVsr5J6FAWKgtLIRIaTGfL6cJqWDrnxv/MuLbuYGCXSmHBualN1xkktKVlzM23EkucChJeJ1AKLULyYSCTZet8rg9aHo5qvoDa4dw5hnZsyBijljqIzncO18tNL/+QucIjfQbR7GKUjb8J5LyR/nAj2afp0xshjsem6LnMgwUej/YhrAATi71pCbUXVflk6C65hcQmLR/TNZ9ZxTvJkTtQyVp2+3EWkoUFo/rD/uljLzy9NKKijeHqjjIwHzoi74NBoL02p5r5LoDdBsujF965HivB/p1kHT10eaxA6OoPw/TzxvwimD5tfmCvqKNiKX0zb965Z57G2XsgR4jv9duecCnOaa8NfIYt8f0pzGfTd652t2bnoeGktuW4DbNW/CBTIuJiRGqgHmjIF9ga5pNWXaFdqefeZa3yAw/KTz7/DgFSCaDTUPMXzSss1SbwMf8Nf8t+ddxpTrjT38C5h4zCgLa350a73Wc5o7qC4hxs+3EDs2b00NC6yORaayjS7DcBROLXK4IAqr/bgEkV5XAjea7RsKzg80ZkO1eYoK+fM+A4yNFZnRSy0uZIcYcwQWebIwLmqRKHa3Za4aFUzIswCDpKerl5pSs9CfkUHBRZ8PtsYzXRyMMgMbqk=

jdk:
- oraclejdk8
android:
  components:
  - tools
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - build-tools-26.0.1
  - android-26
deploy:
  provider: releases
  # The api-key is encrypted like described here: http://docs.travis-ci.com/user/encryption-keys/  (only travis can decrypt the key)
  api_key:
    secure: jfIhIrZ7WS5J80pCMkDqUx8u1RptLBWdz2pWCawRRLDISISUKmHHGEplPuZR7oJ1tlsDJkXVSH7oVlX9wx50yNVB/B8s4iwJO/PO7sRoXQ5nQXIqX/WIqe5lmzcU+ExLw0vhe9MCnQ/G087SG1RascV05k+N1AFokPgb22pL1nkc1S/gc2SWZx6iLWMvdTy9/i+uEMNaLwwTRZBiLopkRr++uz7mOZGG3Py38ENx/UAzJ8M+BPWMfXJLEnxTc9wN5NC1TfqcEbpwX1zMwonMVZs1zOdzznrLdoPC/NgVRVbe+Q61w6zilwiqTowE0R54yi2fOHUOnM4UbHBtx+SOj0b2mnZtae+WMXG4sbfetB6hEmtvt5GvLpEEI7FX0bFPGywEFIa7u/kDoNA/pBcU0Kw7Igb/G4zOR6rCaEgxIhdH3pue5TTCd9axjYfe0InFZAmRkpm1SJLEnn+gMrLYDEu56cgReNpbbxP8K2/sW6D+3AYtwlPUoZ6zABja5bYEz6McwZuDpH8s9x40NrK403sOnUa81qJ2TVLIAR38oO4ljVBtmviPmsnol2tkk0sWAL4a3NPB765SA08S4v7DPnWLujNy0zMXlH4LaN/D9pLdvwJFFL4WNnlA63KC8p6dLQLnB2vxuZ7VcbMAsFWL/wyCYI5d9q8+Lf3UBSHQa6g=
  # Which file(s) to upload
  file: sample/build/outputs/apk/debug/sample-debug.apk
  # do not delete the files we're trying to upload
  skip_cleanup: true
  # only deploy if
  on:
    # we are on this repo
    repo: RowlandOti/CartCounter
    # and we are building a tag
    tags: true
before_install:
- export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
- export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
- export JAVA_HOME=$JAVA8_HOME
- chmod +x gradlew
script:
- "./gradlew clean build --stacktrace"
after_deploy:
- "./gradlew bintrayUpload -PbintrayUser=$BINTRAYUSER -PbintrayKey=$BINTRAYKEY -PdryRun=false --stacktrace"
